import { useTranslation } from 'react-i18next'

/** Copy for the shared travel interface, in all three site languages. */
const copy = {
  uz: {
    eyebrow: 'Sayohat uchun eSIM',
    title: 'Qayerga',
    accent: 'boramiz?',
    lead: 'Yangi manzillar, yaqin aloqalar. Safaringiz uchun internetni yo‘lga chiqishdan oldin tayyorlang.',
    search: 'Qayerga sayohat qilamiz?',
    searchHint: 'Davlat yoki hududni qidiring',
    find: 'Tariflarni ko‘rish',
    popular: 'Keyingi manzilingiz.',
    popularNote: 'Keyingi manzilingiz uchun mos internet paketini toping.',
    all: 'Barcha yo‘nalishlar',
    quick: 'Ommabop:',
    coverage: 'davlat va hudud',
    globeHint: 'Globusni aylantiring. Manzilni tanlang.',
    feature1: 'O‘z raqamingiz siz bilan',
    feature2: 'QR orqali o‘rnatish',
    feature3: 'So‘mda qulay to‘lov',
    how: 'Uch qadam. Va siz aloqadasiz.',
    howNote: 'Aeroportda SIM karta izlashga vaqt ketkazmang. Hammasini safardan oldin tayyorlang.',
    howLink: 'O‘rnatish qo‘llanmasi',
    step1: 'Manzil va tarifni tanlang',
    step1Note: 'Safaringizga mos internet hajmi va muddatini belgilang.',
    step2: 'eSIM’ni o‘rnating',
    step2Note: 'To‘lovdan keyin QR kod va o‘rnatish yo‘riqnomasini olasiz.',
    step3: 'Yetib boring. Ulaning.',
    step3Note: 'Manzilingizda eSIM’ni internet uchun tanlang va sayohatni boshlang.',
    device: 'Telefoningiz safarga tayyormi?',
    deviceNote: 'eSIM sotib olishdan oldin qurilmangiz mosligini tekshiring.',
    deviceCta: 'Qurilmani tekshirish',
    global: 'Bir safar. Bir nechta manzil.',
    globalNote: 'Bir nechta davlatga borasizmi? Hududiy va global eSIM tariflarini ko‘ring.',
    globalCta: 'Global tariflarni ko‘rish',
    faq: 'Savollaringizga javoblar',
    faqNote: 'eSIM bilan ilk sayohatingizmi? Kerakli ma’lumotlar shu yerda.',
    help: 'Yordam markazi',
    menu: 'Menyu',
    navHow: 'Qanday ishlaydi',
    navEnough: 'Menga yetadimi?',
    navMyEsim: 'Mening eSIM’im',
    close: 'Yopish',
    settings: 'Til va ko‘rinish',
    footer: 'Yangi manzillar. Yaqin aloqalar.',
    footerNote: 'Sayohat uchun internet, o‘zingizga qulay tilda.',
    explore: 'Sayohat',
    learn: 'Foydali ma’lumot',
    legal: 'Hujjatlar',
    contact: 'Aloqada bo‘lamiz',
    catalogueTitle: 'Keyingi manzilingiz qayer?',
    catalogueNote: 'Bir davlat, butun hudud yoki dunyo bo‘ylab — safaringizga mos eSIM.',
    countryNote:
      'Safaringizga mos internetni tanlang. QR orqali o‘rnating va yetib borgach ulaning.',
    planTitle: 'O‘zingizga mos tarifni tanlang',
    planNote: 'Internet hajmi, amal qilish muddati va jami narx — barchasi bir joyda.',
    data: 'Internet',
    duration: 'Amal qilish muddati',
    days: 'kun',
    network: 'Tarmoq',
    hotspot: 'Internet ulashish',
    included: 'Mavjud',
    choose: 'Tarifni tanlash',
    total: 'Jami',
    from: 'dan',
    authTitle: 'Qayerda bo‘lsangiz ham,',
    authAccent: 'yaqinlaringiz yoningizda.',
    authNote: 'eSIM’laringiz, safarlaringiz va buyurtmalaringiz — bitta kabinetda.',
    supportTitle: 'Yordam doim yoningizda.',
    supportNote: 'Moslikni tekshirishdan eSIM’ni o‘rnatishgacha — yo‘l-yo‘riq ko‘rsatamiz.',
    guideLabel: 'QulaySIM qo‘llanmasi',
    checkoutLabel: 'Buyurtmani yakunlash',
    checkoutNote: 'Tarifni tekshiring va o‘zingizga qulay usulda to‘lang.',
    empty: 'Hozircha hech narsa topilmadi',
    emptyNote: 'Boshqa davlat nomi bilan qayta qidirib ko‘ring.',
    clear: 'Qidiruvni tozalash',
  },
  en: {
    eyebrow: 'Your travel eSIM',
    title: 'Where to',
    accent: 'next?',
    lead: 'New places. Closer connections. Get your travel data ready before you leave.',
    search: 'Where are we going next?',
    searchHint: 'Search a country or region',
    find: 'Explore plans',
    popular: 'Your next destination.',
    popularNote: 'Find the right data plan for your next destination.',
    all: 'All destinations',
    quick: 'Popular:',
    coverage: 'countries and regions',
    globeHint: 'Spin the globe. Pick your destination.',
    feature1: 'Keep your own number',
    feature2: 'Install with a QR code',
    feature3: 'Convenient payment in UZS',
    how: 'Three steps. You’re connected.',
    howNote: 'Skip the search for a SIM at the airport. Get everything ready before you travel.',
    howLink: 'Installation guide',
    step1: 'Choose your destination and plan',
    step1Note: 'Pick the data allowance and validity that suit your trip.',
    step2: 'Install your eSIM',
    step2Note: 'After payment, get your QR code and installation instructions.',
    step3: 'Arrive. Connect. Explore.',
    step3Note: 'Select your eSIM for mobile data at your destination and enjoy your trip.',
    device: 'Is your phone ready to travel?',
    deviceNote: 'Check device compatibility before buying an eSIM.',
    deviceCta: 'Check my device',
    global: 'One trip. More destinations.',
    globalNote: 'Visiting several countries? Explore regional and global eSIM plans.',
    globalCta: 'Explore global plans',
    faq: 'A little help for your journey',
    faqNote: 'Your first trip with an eSIM? Find the essentials here.',
    help: 'Help center',
    menu: 'Menu',
    navHow: 'How it works',
    navEnough: 'How much data?',
    navMyEsim: 'My eSIMs',
    close: 'Close',
    settings: 'Language and appearance',
    footer: 'New places. Closer connections.',
    footerNote: 'Travel data, in a language that feels like home.',
    explore: 'Explore',
    learn: 'Good to know',
    legal: 'Legal',
    contact: 'Stay in touch',
    catalogueTitle: 'Where will you go next?',
    catalogueNote: 'One country, a whole region or the world — find the eSIM for your trip.',
    countryNote: 'Choose the data you need. Install with a QR code and connect when you arrive.',
    planTitle: 'Find your kind of data plan',
    planNote: 'Data, validity and total price — everything in one place.',
    data: 'Data',
    duration: 'Validity',
    days: 'days',
    network: 'Network',
    hotspot: 'Hotspot',
    included: 'Included',
    choose: 'Choose plan',
    total: 'Total',
    from: 'from',
    authTitle: 'Wherever you go,',
    authAccent: 'keep your people close.',
    authNote: 'Your eSIMs, journeys and orders — all in one account.',
    supportTitle: 'A helping hand, wherever you are.',
    supportNote: 'From device compatibility to installation, we’ll help you find your way.',
    guideLabel: 'The QulaySIM guide',
    checkoutLabel: 'Complete your order',
    checkoutNote: 'Review your plan and choose how to pay.',
    empty: 'No destinations found',
    emptyNote: 'Try searching for another country name.',
    clear: 'Clear search',
  },
  ru: {
    eyebrow: 'eSIM для путешествий',
    title: 'Куда',
    accent: 'едем?',
    lead: 'Новые места, близкие связи. Подготовьте интернет для поездки ещё до вылета.',
    search: 'Куда отправимся?',
    searchHint: 'Найдите страну или регион',
    find: 'Смотреть тарифы',
    popular: 'Следующее направление.',
    popularNote: 'Подберите интернет для следующего направления.',
    all: 'Все направления',
    quick: 'Популярное:',
    coverage: 'стран и регионов',
    globeHint: 'Вращайте глобус. Выберите направление.',
    feature1: 'Ваш номер остаётся с вами',
    feature2: 'Установка по QR-коду',
    feature3: 'Удобная оплата в сумах',
    how: 'Три шага. И вы на связи.',
    howNote: 'Не тратьте время на поиск SIM-карты в аэропорту. Подготовьте всё до поездки.',
    howLink: 'Инструкция по установке',
    step1: 'Выберите страну и тариф',
    step1Note: 'Подберите объём интернета и срок действия для вашей поездки.',
    step2: 'Установите eSIM',
    step2Note: 'После оплаты вы получите QR-код и инструкцию по установке.',
    step3: 'Прилетайте. Подключайтесь.',
    step3Note: 'Выберите eSIM для мобильного интернета по прибытии и начните путешествие.',
    device: 'Ваш телефон готов к поездке?',
    deviceNote: 'Проверьте совместимость устройства перед покупкой eSIM.',
    deviceCta: 'Проверить устройство',
    global: 'Одна поездка. Больше открытий.',
    globalNote: 'Посещаете несколько стран? Выберите региональный или глобальный тариф.',
    globalCta: 'Глобальные тарифы',
    faq: 'Ответы на ваши вопросы',
    faqNote: 'Первая поездка с eSIM? Всё необходимое — здесь.',
    help: 'Центр помощи',
    menu: 'Меню',
    navHow: 'Как это работает',
    navEnough: 'Хватит ли мне?',
    navMyEsim: 'Мои eSIM',
    close: 'Закрыть',
    settings: 'Язык и оформление',
    footer: 'Новые места. Близкие связи.',
    footerNote: 'Интернет в путешествиях на понятном вам языке.',
    explore: 'Направления',
    learn: 'Полезно знать',
    legal: 'Документы',
    contact: 'Будем на связи',
    catalogueTitle: 'Куда отправимся дальше?',
    catalogueNote: 'Одна страна, целый регион или весь мир — найдите eSIM для вашей поездки.',
    countryNote: 'Выберите нужный интернет. Установите по QR-коду и подключитесь по прибытии.',
    planTitle: 'Выберите подходящий тариф',
    planNote: 'Интернет, срок действия и итоговая цена — всё в одном месте.',
    data: 'Интернет',
    duration: 'Срок действия',
    days: 'дней',
    network: 'Сеть',
    hotspot: 'Раздача интернета',
    included: 'Доступна',
    choose: 'Выбрать тариф',
    total: 'Итого',
    from: 'от',
    authTitle: 'Где бы вы ни были,',
    authAccent: 'близкие всегда рядом.',
    authNote: 'Ваши eSIM, поездки и заказы — в одном кабинете.',
    supportTitle: 'Помощь всегда рядом.',
    supportNote: 'От проверки совместимости до установки eSIM — поможем разобраться.',
    guideLabel: 'Руководство QulaySIM',
    checkoutLabel: 'Оформление заказа',
    checkoutNote: 'Проверьте тариф и выберите удобный способ оплаты.',
    empty: 'Направления не найдены',
    emptyNote: 'Попробуйте ввести другое название страны.',
    clear: 'Очистить поиск',
  },
}

export function useDesignCopy() {
  const { i18n } = useTranslation()
  return copy[(i18n.resolvedLanguage?.split('-')[0] as keyof typeof copy) || 'uz'] || copy.uz
}
