// Generated by scripts/build-media.py — do not edit by hand.

export interface MediaVariant {
  w: number
  h: number
  avif: string
  webp: string
}

export const MEDIA: Record<string, MediaVariant[]> = {
  'device-esim': [{ w: 480, h: 704, avif: '/media/device-esim-480.avif', webp: '/media/device-esim-480.webp' }, { w: 900, h: 1321, avif: '/media/device-esim-900.avif', webp: '/media/device-esim-900.webp' }],
  'hero-dark': [{ w: 1024, h: 512, avif: '/media/hero-dark-1024.avif', webp: '/media/hero-dark-1024.webp' }, { w: 1774, h: 887, avif: '/media/hero-dark-1774.avif', webp: '/media/hero-dark-1774.webp' }],
  'hero-light': [{ w: 1024, h: 512, avif: '/media/hero-light-1024.avif', webp: '/media/hero-light-1024.webp' }, { w: 1774, h: 887, avif: '/media/hero-light-1774.avif', webp: '/media/hero-light-1774.webp' }],
  'photos/azerbaijan': [{ w: 480, h: 270, avif: '/media/photos/azerbaijan-480.avif', webp: '/media/photos/azerbaijan-480.webp' }, { w: 900, h: 506, avif: '/media/photos/azerbaijan-900.avif', webp: '/media/photos/azerbaijan-900.webp' }],
  'photos/bali': [{ w: 480, h: 270, avif: '/media/photos/bali-480.avif', webp: '/media/photos/bali-480.webp' }, { w: 900, h: 506, avif: '/media/photos/bali-900.avif', webp: '/media/photos/bali-900.webp' }],
  'photos/china': [{ w: 480, h: 270, avif: '/media/photos/china-480.avif', webp: '/media/photos/china-480.webp' }, { w: 900, h: 506, avif: '/media/photos/china-900.avif', webp: '/media/photos/china-900.webp' }],
  'photos/dubai': [{ w: 480, h: 270, avif: '/media/photos/dubai-480.avif', webp: '/media/photos/dubai-480.webp' }, { w: 900, h: 506, avif: '/media/photos/dubai-900.avif', webp: '/media/photos/dubai-900.webp' }],
  'photos/egypt': [{ w: 480, h: 270, avif: '/media/photos/egypt-480.avif', webp: '/media/photos/egypt-480.webp' }, { w: 900, h: 506, avif: '/media/photos/egypt-900.avif', webp: '/media/photos/egypt-900.webp' }],
  'photos/georgia': [{ w: 480, h: 270, avif: '/media/photos/georgia-480.avif', webp: '/media/photos/georgia-480.webp' }, { w: 900, h: 506, avif: '/media/photos/georgia-900.avif', webp: '/media/photos/georgia-900.webp' }],
  'photos/istanbul': [{ w: 480, h: 270, avif: '/media/photos/istanbul-480.avif', webp: '/media/photos/istanbul-480.webp' }, { w: 900, h: 507, avif: '/media/photos/istanbul-900.avif', webp: '/media/photos/istanbul-900.webp' }],
  'photos/italy': [{ w: 480, h: 270, avif: '/media/photos/italy-480.avif', webp: '/media/photos/italy-480.webp' }, { w: 900, h: 506, avif: '/media/photos/italy-900.avif', webp: '/media/photos/italy-900.webp' }],
  'photos/malaysia': [{ w: 480, h: 270, avif: '/media/photos/malaysia-480.avif', webp: '/media/photos/malaysia-480.webp' }, { w: 900, h: 507, avif: '/media/photos/malaysia-900.avif', webp: '/media/photos/malaysia-900.webp' }],
  'photos/qatar': [{ w: 480, h: 270, avif: '/media/photos/qatar-480.avif', webp: '/media/photos/qatar-480.webp' }, { w: 900, h: 506, avif: '/media/photos/qatar-900.avif', webp: '/media/photos/qatar-900.webp' }],
  'photos/saudi': [{ w: 480, h: 270, avif: '/media/photos/saudi-480.avif', webp: '/media/photos/saudi-480.webp' }, { w: 900, h: 506, avif: '/media/photos/saudi-900.avif', webp: '/media/photos/saudi-900.webp' }],
  'photos/thailand': [{ w: 480, h: 270, avif: '/media/photos/thailand-480.avif', webp: '/media/photos/thailand-480.webp' }, { w: 900, h: 506, avif: '/media/photos/thailand-900.avif', webp: '/media/photos/thailand-900.webp' }],
  'photos/uzbekistan': [{ w: 480, h: 270, avif: '/media/photos/uzbekistan-480.avif', webp: '/media/photos/uzbekistan-480.webp' }, { w: 900, h: 506, avif: '/media/photos/uzbekistan-900.avif', webp: '/media/photos/uzbekistan-900.webp' }],
  'photos/vietnam': [{ w: 480, h: 270, avif: '/media/photos/vietnam-480.avif', webp: '/media/photos/vietnam-480.webp' }, { w: 900, h: 506, avif: '/media/photos/vietnam-900.avif', webp: '/media/photos/vietnam-900.webp' }],
}
